django2/account/urls.py


from django.contrib import admin
from django.urls import path


from . import views
app_name = "account"

urlpatterns = [

	path('account/', views.login_view, name= 'login'),
	path('account/register', views.register_view, name= 'register'),
	path('account/logout', views.logout_view, name= 'logout'),
	#path('comments/<int:id>/delete', views.comment_delete, name = 'delete'),


]











django2/django2/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("comments.urls" ,namespace = 'comments')),
    path('', include("account.urls" ,namespace = 'account')),
    path('', include("posts.urls" ,namespace = 'posts')),
    path('', include("posts.api.urls" ,namespace = 'posts-api')),
    path('', include("comments.api.urls" ,namespace = 'comments-api')),
    path('', include("account.api.urls" ,namespace = 'users')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django2/posts/urls.py



from django.contrib import admin
from django.urls import path
from . import views
app_name = "posts"

urlpatterns = [
    
    path('', views.posts_home, name = 'list'),
    path('posts/create', views.create, name = 'create'),
    path('posts/<int:id>/', views.read, name= 'read'),
    #path('posts/<slug:slug>/', views.read, name= 'read'),
    path('posts/<int:id>/update', views.update, name='update'),
    path('posts/<int:id>/delete', views.delete, name = 'delete')


]

django2/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time
from django.contrib.contenttypes.models import ContentType

# Create your models here.
# MVC
##
#Some defult ModelManager is:
#Post.objects.all()
#Post.objects.create()

class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		#Post.objects.all()= super(PostManager, self).all()
		return super(PostManager, self).filter(draf=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete = True)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique= True)
	image = models.ImageField(null=True, blank= True,
		upload_to=upload_location, 
		width_field= "width_field",
		height_field="height_field")
	draf = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add= False)
	read_time = models.IntegerField(default=0)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	objects = PostManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:read" , kwargs={"id":self.id})
		#return ("posts:read",(),{"slug":self.slug})
		#return "/posts/%s/" %(self.id)

	def get_api_url(self):
		return reverse("posts-api:details" , kwargs={"id":self.id})
	
	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

		

	class Meta:
		ordering = ["-timestamp", "-updated"]

	@property
	def comments(self):
		item = self
		qs = Comment.objects.filter_by_instance(item)
		return qs

	@property
	def get_content_type(self):
		item = self
		content_type = ContentType.objects.get_for_model(item.__class__)
		return content_type



def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug= slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)

	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)
	if instance.content:
		html_string = instance.get_markdown()
		read_time = get_read_time(html_string)
		instance.read_time = read_time
pre_save.connect(pre_save_post_receiver, sender=Post)
			

django2/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block head_title %}Try Django 2.0{% endblock head_title %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/base.css">
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<style>
		{% block style %}{% endblock style %}
	</style>
	{% block head_extra %} {% endblock head_extra %}
</head>
<body>

	<div id="fb-root"></div>
	<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=1958768794430932&autoLogAppEvents=1"></script>
	{% include "messages.html" %}
	<div class="container">
		<ol class="breadcrumb">
			<li><a href='{% url "posts:list" %}'>Home</a></li>
			{% block post_detail_link %}
			{% endblock %}

			{% if request.user.is_authenticated %}
			<li class="pull-left"><a href="{% url 'account:register'%}">Register</a></li>
			<li class="pull-left"><a href="{% url 'account:login'%}">Login</a></li>
			{% else %}
			<li class="pull-right"><a href="{% url 'account:logout'%}">Logout</a></li>
			{% endif %}
		</ol>

		{% block content %} {% endblock content %}

	</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="http://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.2/marked.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".content-markdown").each(function(){
		var content = $(this).text()
		var markedContent = marked(content)
		$(this).html(markedContent)
	})
	$(".post-detail-item img").each(function(){
		$(this).addClass("img-fluid")
			
	})


	//var titleInput = $("#id_title");
	//$('#preview-tital').text(titleInput.val())


	//var contentInput = $("#id_content");

	//function setContent(value){
		//var markedContent = marked(value)
		//$("#preview-content").html(markedContent)
		//$("#preview-content img").each(function()){
			//$(this).addClass("img-fluid")
		//}
	//}
	//setContent(contentInput.val())

	//contentInput.keyup(function(){
		//var newContent = $(this).val()
		//setContent(newContent)

	//})

	$(".comment-reply-btn").click(function(event){
		event.preventDefault();
		$(this).parent().next(".comment-reply").fadeToggle();
	})


		
})
</script>
</body>
</html>




django2/templates/comment_delete.html
{% extends "base.html"%}

{% block content %}

<div>
	
	<form method="POST" action="">{% csrf_token %}
		<p><p>Are you sure you want to delete: "{{ object.content }}"?</p></p>
		<input type="submit" name="delete" value="Delete" class="btn btn-warning">
		<a href="{{ comment.get_absolute_url }}">Cancel</a>
		
	</form>

</div>


{% endblock content %}

django2/templates/comment_tread.html
{% extends "base.html"%}
{% load urlify %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="col-sm-12 col-sm-offset-3">
		

		<p class="mb-0">{{ comment.content }}</p>
  			<footer>via {{ comment.user}} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count}} Reply{% if comment.children.count > 1 %}s{% endif %} | {% endif %} {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</footer>
  			<!-- all reply and reply form -->
  			<div>
  				{% for reply in comment.children %}
  				<blockquote class="blockquote">
  					<p class="mb-0">{{ reply.content }}</p>
  					<footer>via {{ reply.user}} | {{ reply.timestamp|timesince }} ago {% if request.user == reply.user %}<a href="{{ reply.get_delete_url }}">Delete</a>{% endif %}</footer>
  				</hr>
  			</br>
  				</blockquote>

  				{% endfor %}
  				{% if request.user.is_authenticated %}
				<form method="POST" action=".">{% csrf_token %}
						{{ form|crispy }}
					<input type="hidden" name="parent_id" value="{{ comment.id }}">
					<input type="submit" value="Reply" name="" class="btn btn-default">
				</form>
				{% else %}
						<p>You must have to login</p>
				{% endif %} 
			</div>
			
		
	</div>
	</div>

	
{% endblock content %}


django2/templates/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<!--<div class="row">
<div class="col-sm-6">
	<h1>Preview</h1>
</div>

<div class="content-preview">
	<h3 id="preview-title"></h3>
	<p id="preview-content"></p>
</div>
-->

<div class="col-sm-6 col-sm-offset-6" >
	<h1>Make a new Post</h1>
	<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
	{{ form|crispy}}
	<input type="submit" name="" value="Post_create" />
	
	</form>

</div>

{% endblock content %}

django2/templates/login_view.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}


<div class="col-sm-6 col-sm-offset-3" >

	<h1>{{ title }}</h1>
	<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
	{{ form|crispy }}
	<input type="submit" name="" value="{{ title }}" />
	
	</form>

</div>

{% endblock content %}

django2/templates/messages.html


{% if messages %}
		<ul class="messages">
    	{% for message in messages %}
    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_teg" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    	</ul>
	{% endif %}

django2/templates/post_home.html
{% extends "base.html" %}

{% block content %}


<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}} is working</h1>


<form method="GET" action="" class="row" >
    <div class="col-sm-8">
    <div class="input-group">
        <input class="form-control" type="text" name="q" placeholder="search posts" value="{{ request.GET.q }}" />
        <span class="input-group-btn">
            <!--<input class="btn btn-default" type="submit" value="Search" />-->
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span>
    </div>
    </div>
</form>


</br>

{%for obj in objects_list%}
<div class="row">
<div class="col-sm-12">
    <div class="thumbnail">
    	{% if obj.image %}
    		<img src="{{ obj.image.url }}" class="img-fluid"/>
    	{% endif %}
     	<div class="post-detail-item">
            {% if obj.draf %}<h3>Draft</h3>{% endif %} {%if obj.publish > today %}<h3>Future Post</h3>{% endif %}
        <h3><a href='{{obj.get_absolute_url}}'>{{obj.title}}</a><small>{{obj.publish}} </small></h3>
        <p class="">{{obj.get_markdown|truncatechars_html:120}}</p>
        <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
</div>
<hr>
{%endfor%}


<div class="pagination">
    <span class="step-links">
        {% if objects_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ objects_list.previous_page_number }}&{% if request.GET.q %}q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects_list.number }} of {{ objects_list.paginator.num_pages }}.
        </span>

        {% if objects_list.has_next %}
            <a href="?page={{ objects_list.next_page_number }}& {% if request.GET.q %}q={{ request.GET.q }}{% endif %}">next</a>
            <a href="?page={{ objects_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>

</div>
{% endblock %}
















django2/templates/read.html
{% extends "base.html"%}
{% load urlify %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="col-sm-12 col-sm-offset-3">
		{% if item.image %}
		<img src="{{ item.image.url }}" class="img-fluid"/>
		{% endif %}
	<h1>{{item.title}} <small>{% if item.draf %} <span style="color:red;">Draf</span> {% endif %} {{item.publish}}</small></h1>


		{{item.updated}}
		<p>Author : {{item.user}}</p>
		<p>Read time:{{ item.read_time }}</p>
	<p><div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
<!-- 
	<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Facebook</a>
	<a href="https://twitter.com/home?status={{ item.content|urlify }}%20{{ request.build_absolute_uri }}">Twitter</a>
	<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a></br>
	</p>
	</br>
-->
	</br>
<div class="col-sm-10 col-sm-offset-1 ">
	<div class="post-detail-item">{{item.get_markdown}}</div>
		

</br>
</br>
	<div>
		<p>comments</p>

		<!-- all comments and reply form -->
		{% for comment in comments %}
			<blockquote class="blockquote">
  				<p class="mb-0">{{ comment.content }}</p>
  				<footer><small>via {{ comment.user}} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count}} Reply {% if comment.children.count > 1 %}s{% endif %} | {% endif %} {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}| <a href="{{ comment.get_absulte_url }}">Reply</a></small></footer>
  				<!-- all reply and reply form -->
  				<div class="comment-reply"  >
  					{% for reply in comment.children %}
  					<blockquote class="blockquote">
  						<p class="mb-0">{{ reply.content }}</p>
  						<footer>via {{ reply.user}} | {{ reply.timestamp|timesince }} ago</footer>
  					</blockquote>
  					{% endfor %}
  					{% if request.user.is_authenticated %}
					<form method="POST" action=".">{% csrf_token %}
						{{ comment_form|crispy }}
						<input type="hidden" name="parent_id" value="{{ comment.id }}">
						<input type="submit" value="Reply" name="" class="btn btn-default">
					</form>
					{% else %}
						<p>You must have to login</p>
					{% endif %} 
				</div>
			</blockquote>
		{% endfor %}
					<!-- a comments form -->
		{% if request.user.is_authenticated %}
		<form method="POST" action=".">{% csrf_token %}
			{{ comment_form|crispy }}
			<input type="submit" value="Comment" name="" class="btn btn-default">
		</form>
		{% else %}
		<p>You must have to login</p>
		{% endif %} 
	</div>
		



	<!-- <div class="fb-comments" data-href='{{ request.build_absolute_uri }}' data-numposts="5"></div> -->


	</div>

</div>

	
{% endblock content %}
